### ISSUE TITLE
Not Seeing Notifications

### ISSUE THREAD

**Issue by NewToJailbreak** [Baw-Appie/Axon#12]
Love the tweak! But it seems to not give me a notification of my messages when I get them. Is that something with the tweak or another setting?

**Comment by Kingslayer9988** [comment]
Same here

**Comment by Baw-Appie** [comment]
Can you explain in detail?

**Comment by Kingslayer9988** [comment]
I reinstalled eveything restored rootfs in checkrain now its working :)
