### ISSUE TITLE
Incompatibilidad entre “Axon” y “Centaur”

### ISSUE THREAD

**Issue by rully1968** [Baw-Appie/Axon#15]
Hola. solo para informar que al instalar el tweak “Centaur” y el tweak “Axon” pude ver que no existe u optimo funcionamiento del tweak Centaur, al desinstalar Axon si funciona correctamente Centaur... ojala en un futuro puedan juntos ser compatibles estos 2 grandes tweaks

**Comment by Baw-Appie** [comment]
**This is not Axon's issue.**
This issue should be resolved by the developer of Centaur
