### ISSUE TITLE
Clear all notifications function

### ISSUE THREAD

**Issue by melvinosenga** [Baw-Appie/Axon#16]
I cant clear all my notifications. Can we have this function?

**Comment by Baw-Appie** [comment]
Can you explain in detail?

**Comment by melvinosenga** [comment]
Hi,

Thanks for your reply. In iOS13 you normally have a button to clear all notifications at once in the notification center. I’ve noticed that by long press/3D touching the app icon you can delete multiple notifications, but you can’t delete all notifications from all apps at once.

This means I have to 3D touch all the individual apps and delete the notifications for each app to clear my notification center. I’d love to have the option added to clear all notifications at once to the 3d touch/long press menu.

**Comment by Baw-Appie** [comment]
![IMG_0001](https://user-images.githubusercontent.com/15670271/76045070-77a59300-5f9f-11ea-85ac-3783f873f8ac.png)
It will be added in the 0.5 update.
