### ISSUE TITLE
Axon does not remove some notifications

### ISSUE THREAD

**Issue by Greigh** [Baw-Appie/Axon#2]
iPhone XS Max 12.4 
Axon 0.2.3

Axon does not let me Clear Notifications and doesn’t show any Notifications exist. A respring temporarily fixes. Attached a photo showing no notifications. Pressing Clear All does not work.

**Comment by Greigh** [comment]
Well it will not let me upload a screenshot on Mobile, so I will submit one tomorrow on my MacBook.

**Comment by Baw-Appie** [comment]
Are you using iOS 13?

**Comment by Greigh** [comment]
iOS 12.4 iPhone XS Max unc0ver

--
Greigh Canary

**Comment by Baw-Appie** [comment]
Does Clear All work with Axon 0.3.0?

**Comment by Greigh** [comment]
Unfortunately nope. It won’t even clear with notifications there now.

**Comment by JannikCrack** [comment]
I have the same issue iOS 13.2.3 iPhone X checkra1n. I get and message, read it and then the message doesent disappear if I press on it it doesent open and i can’t clear it. If you want I can send a video

**Comment by Baw-Appie** [comment]
> I have the same issue iOS 13.2.3 iPhone X checkra1n. I get and message, read it and then the message doesent disappear if I press on it it doesent open and i can’t clear it. If you want I can send a video

It would be nice to have a video 😀

**Comment by JannikCrack** [comment]
Here are some videos. 😅

https://imgur.com/a/lPvUXyv

**Comment by Baw-Appie** [comment]
I think other tweak is interfering with Axon..

**Comment by JannikCrack** [comment]
I also have this issue if I disable all tweaks and just have Axon enabled. I also tried rootFS

**Comment by Baw-Appie** [comment]
> I also have this issue if I disable all tweaks and just have Axon enabled. I also tried rootFS

Do you have Telegram?
I need a test.

**Comment by Greigh** [comment]
I do. I’ll message you Baw-Appie.

**Comment by JannikCrack** [comment]
Yes I have https://t.me/JannikCrack
