### ISSUE TITLE
Notification clear button being overlapped

### ISSUE THREAD

**Issue by Hermezlink** [Baw-Appie/Axon#24]
![9C80C2D4-10C9-400E-8A78-48BE5FB4E18C](https://user-images.githubusercontent.com/62443647/77196232-8c5a4e80-6aa8-11ea-940f-bcab0116303c.png)

**Comment by Hermezlink** [comment]
You can see there are two “X” (Clear) buttons and the notification centre shows up too and looks off

**Comment by Baw-Appie** [comment]
duplicated #22
