### ISSUE TITLE
With Axon, the text “notification center” is overlay.

### ISSUE THREAD

**Issue by jacman23** [Baw-Appie/Axon#29]
![B7883D2B-3460-4EE5-90A8-DC711DCC7456](https://user-images.githubusercontent.com/41385058/79059272-838b1180-7c3d-11ea-9613-78f64d9a612f.png)
 iOS 13.3.1 
Iphone 11 
With Axon, the text “notification center” is overlay.

**Comment by Greigh** [comment]
Same issue. XS Max. unc0ver. 13.3. I sent you a message in Telegram about it @Baw-Appie.
