### ISSUE TITLE
The "Notification Center" text disappears under certain conditions

### ISSUE THREAD

**Issue by We7dy** [Baw-Appie/Axon#3]
I noticed that after installing the tweak, when I have notifications of different applications and I do a respring, if I switch from one application to another without clicking on the current notification again, the **Notification Center** text disappears. However, this bug does not occur if I click on the active notification to remove it and click on another notification from a different application.

[You can take a closer look at it in video](https://imgur.com/a/Z0LA9mA)

**Comment by We7dy** [comment]
I noticed another bug with this text, I have several notifications in two different applications, but for some reason, in one of them they are not grouped, so the **Notification Center** text does not appear.

https://imgur.com/a/mR0fGfz

**Comment by Baw-Appie** [comment]
"Notification Center" header has been removed.
