### ISSUE TITLE
Axon Bug

### ISSUE THREAD

**Issue by 301nav** [Baw-Appie/Axon#34]
there is a bug where the text "notification center" is displayed with the x button, which is all being overlapped by the app name.
![BEF15C1A-DEA7-491B-B3E8-5CFC7669BCE5](https://user-images.githubusercontent.com/64512105/80556420-84dc6e00-89a1-11ea-92c9-6e35c079fb17.png)
![183B26B5-71B6-428E-BBBF-A8994C3D93EA](https://user-images.githubusercontent.com/64512105/80556421-85750480-89a1-11ea-856e-ceb96f3752cf.png)

**Comment by Baw-Appie** [comment]
Fixed.
