### ISSUE TITLE
Crops the style for Axon

### ISSUE THREAD

**Issue by xShahRukh** [Baw-Appie/Axon#36]
As in the image you can see the issue.
FYI, I have also installed NextAlarm13 tweak which shows in locksreen

![ECF9BB10-4AB7-42A9-B465-7FC09D196EBF](https://user-images.githubusercontent.com/20381819/81156740-e1441c80-8fa3-11ea-8e43-006b175f544a.png)

**Comment by Baw-Appie** [comment]
Fixed.
