### ISSUE TITLE
[Feature Request] Ability to have icons at the bottom of the screen

### ISSUE THREAD

**Issue by Rougemoot** [Baw-Appie/Axon#4]
Hey, not sure this is the best place to leave this, but I'd really like the ability to have the icons on the bottom of the screen when I have notifications. I think Priority Hub used to have that option back in the day and it felt more natural to me because it was closer to my thumb.

Thanks!

**Comment by Baw-Appie** [comment]
Added in Axon 1.0! It will be available soon!
