### ISSUE TITLE
Un-dismissable “Clear all button”

### ISSUE THREAD

**Issue by ghost** [Baw-Appie/Axon#45]
With Axon enabled I get a bizarre unusable “X” clear all button on the left side of my notifications that can’t be interacted with. This is on my iPad Mini 5 on iOS 12.2.

Picture: https://imgur.com/a/zbLBP7u

**Comment by mattp12** [comment]
This is actually a bug with OneNotify and it's Hide "Notification Center" Text option. After disabling this the X goes away.
If you don't have OneNotify then I don't know.
