### ISSUE TITLE
Axon vertical mode is overlapping the musicplayer

### ISSUE THREAD

**Issue by MrGcGamer** [Baw-Appie/Axon#5]
Basically just what the title says

**Comment by Baw-Appie** [comment]
Are you using iOS 13?

**Comment by MrGcGamer** [comment]
Yes I am on iOS 13.2.3

**Comment by levianthony** [comment]
I have this same issue. I have them lining up vertically on the right and I cannot use my mini music player controls. Any fixes to this? Can the notification locations be a little lower on the lock screen so it doesn’t interfere?
