### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by KhaledQ-SA** [Baw-Appie/Axon#55]
Hello there, I’m a huge fan of your tweak, it’s one of my best tweaks but there is a small issue with latest jailbreak 13.5 it’s not stable and interfering with my other tweak (AutoUnlockX).

I know you’re working hard and I understand that but please try to fix it ASAP.

Take care and peace with love ~ SA

**Comment by Baw-Appie** [comment]
Duplicated #42

**Comment by KhaledQ-SA** [comment]
It seems that I’m not the only one who g8ves a feedback, anywho when it will be fixed?
